### ISSUE TITLE
Property "ki_keywords not found in symbol error

### ISSUE THREAD

**Issue by MarvFPV** [Projektanker/kicad-db-lib#60] opened 2023-06-01 11:17 UTC
My symbol library does not have the ki_symbol attribute filled for any symbol. 
Thus, kicad also does not create that property for this select footprint in the .kicad_sym file. 
kicad-db-lib seems to expect that property, then throws an error when it can't find it.

Is there any way of getting around this issue?

**Comment by MarvFPV** [comment] 2023-06-01 11:49
update, samet hing happens with the "description" property.

**Comment by SebastianRumohr** [comment] 2023-06-07 08:37
Could you please send me one of your symbol library files in question and give me an example ? Otherwise I'm not able to reproduce the bug.

**Comment by SebastianRumohr** [comment] 2023-06-15 14:48
I finally managed to reproduce the bug. It should be fixed with [version 3.0.1](https://github.com/Projektanker/kicad-db-lib/releases/tag/3.0.1).

**Closed** 2023-06-15 14:48 UTC
